# Version top-level element is obsolete
# https://docs.docker.com/reference/compose-file/version-and-name/

name: mijung

services:
  db:
    image: mysql:8.4.1
    volumes:
      - "mysql_data:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Seoul
      LANG: C.UTF-8
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    # expose:
    #   - "3306"
    ports:
      - "3306:3306"
    networks:
      - mijung_net
    container_name: mijung_db

  webserver:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf:/etc/nginx/ssl/:ro
    networks:
      - mijung_net
    container_name: nginx

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    networks:
      - mijung_net
    container_name: certbot

  backend:
    image: vaaastlake/mijung_backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    expose:
      - "8080"
    networks:
      - mijung_net
    container_name: mijung_backend

  fastApi:
    build:
      context: ./fastapi
      target: builder
    environment:
      PORT: 8000
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    networks:
      - mijung_net
    container_name: mijung_fastapi

volumes:
  mysql_data:

networks:
  mijung_net:
    driver: bridge
