// 이 파일은 모의 API 데이터를 제공하는 역할을 합니다.
// 실제 API가 준비되지 않았거나 개발 중에 테스트를 위해 사용됩니다.

// 이 모의 데이터를 사용하려면 다음과 같이 가져올 수 있습니다:
// import { mockData } from 'src/shared/api/mock';
//
// 그런 다음 mockData.ingredients 또는 mockData.recipes를 사용하여
// 각각 재료 목록이나 레시피 목록에 접근할 수 있습니다.

export const mockData = {
  ingredients: [
    {
      id: 1,
      name: '사과',
      retailUnit: 'g',
      retailUnitsize: '100',
      image: 'https://picsum.photos/150/100',
      price: '1200',
      changeRate: 5.2,
      changePrice: 60,
    },
    {
      id: 2,
      name: '배',
      retailUnit: 'g',
      retailUnitsize: '100',
      image: 'https://picsum.photos/150/100',
      price: '1500',
      changeRate: -3.1,
      changePrice: -48,
    },
    {
      id: 3,
      name: '바나나',
      retailUnit: 'g',
      retailUnitsize: '100',
      image: 'https://picsum.photos/150/100',
      price: '800',
      changeRate: 2.5,
      changePrice: 20,
    },
    {
      id: 4,
      name: '당근',
      retailUnit: 'g',
      retailUnitsize: '100',
      image: 'https://picsum.photos/150/100',
      price: '500',
      changeRate: -1.8,
      changePrice: -9,
    },
    {
      id: 5,
      name: '닭가슴살',
      retailUnit: 'g',
      retailUnitsize: '100',
      image: 'https://picsum.photos/150/100',
      price: '1800',
      changeRate: 0.5,
      changePrice: 9,
    },
    {
      id: 6,
      name: '달걀',
      retailUnit: '개',
      retailUnitsize: '1',
      image: 'https://picsum.photos/150/100',
      price: '250',
      changeRate: 4.2,
      changePrice: 10,
    },
    {
      id: 7,
      name: '우유',
      retailUnit: 'ml',
      retailUnitsize: '1000',
      image: 'https://picsum.photos/150/100',
      price: '2500',
      changeRate: -2.3,
      changePrice: -59,
    },
    {
      id: 8,
      name: '두유',
      retailUnit: 'ml',
      retailUnitsize: '1000',
      image: 'https://picsum.photos/150/100',
      price: '2200',
      changeRate: 1.4,
      changePrice: 30,
    },
    {
      id: 9,
      name: '토마토',
      retailUnit: 'g',
      retailUnitsize: '100',
      image: 'https://picsum.photos/150/100',
      price: '700',
      changeRate: -0.7,
      changePrice: -5,
    },
    {
      id: 10,
      name: '방울토마토',
      retailUnit: 'g',
      retailUnitsize: '100',
      image: 'https://picsum.photos/150/100',
      price: '900',
      changeRate: 3.3,
      changePrice: 29,
    },
    {
      id: 11,
      name: '양파',
      retailUnit: 'g',
      retailUnitsize: '100',
      image: 'https://picsum.photos/150/100',
      price: '400',
      changeRate: 1.2,
      changePrice: 5,
    },
    {
      id: 12,
      name: '감자',
      retailUnit: 'g',
      retailUnitsize: '100',
      image: 'https://picsum.photos/150/100',
      price: '600',
      changeRate: -2.5,
      changePrice: -15,
    },
    {
      id: 13,
      name: '고구마',
      retailUnit: 'g',
      retailUnitsize: '100',
      image: 'https://picsum.photos/150/100',
      price: '800',
      changeRate: 3.8,
      changePrice: 29,
    },
    {
      id: 14,
      name: '브로콜리',
      retailUnit: 'g',
      retailUnitsize: '100',
      image: 'https://picsum.photos/150/100',
      price: '1000',
      changeRate: -1.5,
      changePrice: -15,
    },
    {
      id: 15,
      name: '시금치',
      retailUnit: 'g',
      retailUnitsize: '100',
      image: 'https://picsum.photos/150/100',
      price: '700',
      changeRate: 2.1,
      changePrice: 14,
    },
    {
      id: 16,
      name: '오이',
      retailUnit: 'g',
      retailUnitsize: '100',
      image: 'https://picsum.photos/150/100',
      price: '500',
      changeRate: -0.8,
      changePrice: -4,
    },
    {
      id: 17,
      name: '파프리카',
      retailUnit: 'g',
      retailUnitsize: '100',
      image: 'https://picsum.photos/150/100',
      price: '1200',
      changeRate: 4.5,
      changePrice: 52,
    },
    {
      id: 18,
      name: '버섯',
      retailUnit: 'g',
      retailUnitsize: '100',
      image: 'https://picsum.photos/150/100',
      price: '900',
      changeRate: -3.2,
      changePrice: -30,
    },
    {
      id: 19,
      name: '표고버섯',
      retailUnit: 'g',
      retailUnitsize: '100',
      image: 'https://picsum.photos/150/100',
      price: '1500',
      changeRate: 2.7,
      changePrice: 39,
    },
    {
      id: 20,
      name: '새송이버섯',
      retailUnit: 'g',
      retailUnitsize: '100',
      image: 'https://picsum.photos/150/100',
      price: '1100',
      changeRate: -1.9,
      changePrice: -21,
    },
    {
      id: 21,
      name: '마늘',
      retailUnit: 'g',
      retailUnitsize: '100',
      image: 'https://picsum.photos/150/100',
      price: '800',
      changeRate: 3.5,
      changePrice: 27,
    },
    {
      id: 22,
      name: '생강',
      retailUnit: 'g',
      retailUnitsize: '100',
      image: 'https://picsum.photos/150/100',
      price: '1000',
      changeRate: -2.8,
      changePrice: -29,
    },
    {
      id: 23,
      name: '대파',
      retailUnit: 'g',
      retailUnitsize: '100',
      image: 'https://picsum.photos/150/100',
      price: '400',
      changeRate: 1.7,
      changePrice: 7,
    },
    {
      id: 24,
      name: '쪽파',
      retailUnit: 'g',
      retailUnitsize: '100',
      image: 'https://picsum.photos/150/100',
      price: '600',
      changeRate: -1.3,
      changePrice: -8,
    },
    {
      id: 25,
      name: '고추',
      retailUnit: 'g',
      retailUnitsize: '100',
      image: 'https://picsum.photos/150/100',
      price: '700',
      changeRate: 2.9,
      changePrice: 20,
    },
    {
      id: 26,
      name: '청양고추',
      retailUnit: 'g',
      retailUnitsize: '100',
      image: 'https://picsum.photos/150/100',
      price: '900',
      changeRate: -2.2,
      changePrice: -20,
    },
    {
      id: 27,
      name: '홍고추',
      retailUnit: 'g',
      retailUnitsize: '100',
      image: 'https://picsum.photos/150/100',
      price: '800',
      changeRate: 3.1,
      changePrice: 24,
    },
    {
      id: 28,
      name: '호박',
      retailUnit: 'g',
      retailUnitsize: '100',
      image: 'https://picsum.photos/150/100',
      price: '600',
      changeRate: -1.6,
      changePrice: -10,
    },
    {
      id: 29,
      name: '애호박',
      retailUnit: 'g',
      retailUnitsize: '100',
      image: 'https://picsum.photos/150/100',
      price: '700',
      changeRate: 2.3,
      changePrice: 16,
    },
    {
      id: 30,
      name: '단호박',
      retailUnit: 'g',
      retailUnitsize: '100',
      image: 'https://picsum.photos/150/100',
      price: '1000',
      changeRate: -3.5,
      changePrice: -36,
    },
    {
      id: 31,
      name: '가지',
      retailUnit: 'g',
      retailUnitsize: '100',
      image: 'https://picsum.photos/150/100',
      price: '800',
      changeRate: 1.8,
      changePrice: 14,
    },
    {
      id: 32,
      name: '상추',
      retailUnit: 'g',
      retailUnitsize: '100',
      image: 'https://picsum.photos/150/100',
      price: '500',
      changeRate: -2.1,
      changePrice: -11,
    },
    {
      id: 33,
      name: '깻잎',
      retailUnit: 'g',
      retailUnitsize: '100',
      image: 'https://picsum.photos/150/100',
      price: '600',
      changeRate: 3.7,
      changePrice: 21,
    },
    {
      id: 34,
      name: '콩나물',
      retailUnit: 'g',
      retailUnitsize: '100',
      image: 'https://picsum.photos/150/100',
      price: '300',
      changeRate: -1.2,
      changePrice: -4,
    },
    {
      id: 35,
      name: '숙주나물',
      retailUnit: 'g',
      retailUnitsize: '100',
      image: 'https://picsum.photos/150/100',
      price: '400',
      changeRate: 2.5,
      changePrice: 10,
    },
    {
      id: 36,
      name: '고사리',
      retailUnit: 'g',
      retailUnitsize: '100',
      image: 'https://picsum.photos/150/100',
      price: '1500',
      changeRate: -3.8,
      changePrice: -59,
    },
    {
      id: 37,
      name: '도라지',
      retailUnit: 'g',
      retailUnitsize: '100',
      image: 'https://picsum.photos/150/100',
      price: '2000',
      changeRate: 4.2,
      changePrice: 81,
    },
    {
      id: 38,
      name: '연근',
      retailUnit: 'g',
      retailUnitsize: '100',
      image: 'https://picsum.photos/150/100',
      price: '1200',
      changeRate: -2.7,
      changePrice: -33,
    },
    {
      id: 39,
      name: '우엉',
      retailUnit: 'g',
      retailUnitsize: '100',
      image: 'https://picsum.photos/150/100',
      price: '1000',
      changeRate: 1.9,
      changePrice: 19,
    },
    {
      id: 40,
      name: '미역',
      retailUnit: 'g',
      retailUnitsize: '100',
      image: 'https://picsum.photos/150/100',
      price: '800',
      changeRate: -1.5,
      changePrice: -12,
    },
    {
      id: 41,
      name: '김',
      retailUnit: 'g',
      retailUnitsize: '100',
      image: 'https://picsum.photos/150/100',
      price: '1500',
      changeRate: 3.3,
      changePrice: 48,
    },
    {
      id: 42,
      name: '다시마',
      retailUnit: 'g',
      retailUnitsize: '100',
      image: 'https://picsum.photos/150/100',
      price: '1000',
      changeRate: -2.4,
      changePrice: -25,
    },
    {
      id: 43,
      name: '멸치',
      retailUnit: 'g',
      retailUnitsize: '100',
      image: 'https://picsum.photos/150/100',
      price: '1200',
      changeRate: 2.8,
      changePrice: 33,
    },
    {
      id: 44,
      name: '새우',
      retailUnit: 'g',
      retailUnitsize: '100',
      image: 'https://picsum.photos/150/100',
      price: '2500',
      changeRate: -3.6,
      changePrice: -93,
    },
    {
      id: 45,
      name: '오징어',
      retailUnit: 'g',
      retailUnitsize: '100',
      image: 'https://picsum.photos/150/100',
      price: '1800',
      changeRate: 4.1,
      changePrice: 71,
    },
    {
      id: 46,
      name: '문어',
      retailUnit: 'g',
      retailUnitsize: '100',
      image: 'https://picsum.photos/150/100',
      price: '3000',
      changeRate: -2.9,
      changePrice: -90,
    },
    {
      id: 47,
      name: '낙지',
      retailUnit: 'g',
      retailUnitsize: '100',
      image: 'https://picsum.photos/150/100',
      price: '2200',
      changeRate: 3.5,
      changePrice: 75,
    },
    {
      id: 48,
      name: '조개',
      retailUnit: 'g',
      retailUnitsize: '100',
      image: 'https://picsum.photos/150/100',
      price: '1500',
      changeRate: -1.7,
      changePrice: -26,
    },
    {
      id: 49,
      name: '굴',
      retailUnit: 'g',
      retailUnitsize: '100',
      image: 'https://picsum.photos/150/100',
      price: '2000',
      changeRate: 2.6,
      changePrice: 51,
    },
    {
      id: 50,
      name: '전복',
      retailUnit: 'g',
      retailUnitsize: '100',
      image: 'https://picsum.photos/150/100',
      price: '5000',
      changeRate: -4.2,
      changePrice: -219,
    },
  ],
  recipes: [
    { id: 1, word: '김치찌개' },
    { id: 2, word: '된장찌개' },
    { id: 3, word: '부대찌개' },
    { id: 4, word: '비빔밥' },
    { id: 5, word: '불고기' },
    { id: 6, word: '삼겹살' },
    { id: 7, word: '파스타' },
    { id: 8, word: '크림파스타' },
    { id: 9, word: '토마토파스타' },
    { id: 10, word: '피자' },
    { id: 11, word: '스테이크' },
    { id: 12, word: '샐러드' },
    { id: 13, word: '시저샐러드' },
    { id: 14, word: '오믈렛' },
    { id: 15, word: '라면' },
    { id: 16, word: '김밥' },
    { id: 17, word: '참치김밥' },
    { id: 18, word: '떡볶이' },
    { id: 19, word: '치즈떡볶이' },
    { id: 20, word: '치킨' },
    { id: 21, word: '양념치킨' },
    { id: 22, word: '후라이드치킨' },
    { id: 23, word: '카레' },
    { id: 24, word: '짜장면' },
    { id: 25, word: '짬뽕' },
    { id: 26, word: '초밥' },
    { id: 27, word: '연어초밥' },
    { id: 28, word: '돈까스' },
    { id: 29, word: '치즈돈까스' },
    { id: 30, word: '고구마맛탕' },
    { id: 31, word: '잡채' },
    { id: 32, word: '갈비찜' },
    { id: 33, word: '닭갈비' },
    { id: 34, word: '감자탕' },
    { id: 35, word: '순두부찌개' },
    { id: 36, word: '계란말이' },
    { id: 37, word: '오징어볶음' },
    { id: 38, word: '제육볶음' },
    { id: 39, word: '닭볶음탕' },
    { id: 40, word: '미역국' },
    { id: 41, word: '육개장' },
    { id: 42, word: '설렁탕' },
    { id: 43, word: '갈비탕' },
    { id: 44, word: '냉면' },
    { id: 45, word: '물냉면' },
    { id: 46, word: '비빔냉면' },
    { id: 47, word: '콩국수' },
    { id: 48, word: '칼국수' },
    { id: 49, word: '수제비' },
    { id: 50, word: '떡국' },
  ],
};
